name: CI/CD Pipeline

# When to run: on every push to main branch
on:
  push:
    branches: [ main ]

jobs:
  # Job 1: Test and Build Docker Image
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Install dependencies and test
    - name: Install and Test
      run: |
        npm install
        npm test

    # Step 4: Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-demo-app:latest .

  # Job 2: Push to Docker Hub
  push-to-dockerhub:
    needs: build  # This job depends on build job
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker image
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-demo-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-demo-app:latest